# Maven
- task: kiuwan-baseline-analysis-task@2
  inputs:
    kiuwanConnection: 'Kiuwan cloud'
    projectnameselector: 'kiuwanapp'
    kiuwanappname: '$TMP'
    analysislabel: 'devops'
    includeinsight: false
    uploadsnippets: true
    uploadfiles: false
    skipclones: false
    overridedotkiuwan: false
    overrideappmodel: false
    dbanalysis: false
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
