name: Kiuwan

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    - name: Kiuwan Baseline Analysis
      uses: eboronat/KiuwanBaselineAction@v1.3
      with:
          kiuwanbaseurl: https://www.kiuwan.com
          project: finanzas-backend-application
          userid: ${{ secrets.KIUWAN_USER}}
          password: ${{ secrets.KIUWAN_PASSWORD}}
          
